#include <stdio.h>
#include "game.h"
#include "random.h"
#include "players.h"

int main()
{
    
    reset_game();//---------------initialize game and reset variables............................................................
    Greetings();//-----------------greet player....................................................................................
    //input_player_count();//-------input player count...................................................................................
    // input_player_profiles();//----input player profiles....................................................................................
    // input_game_count();//---------input game count........................................................................................
    // run_game();//-----------------arguments: players

}